### PR TITLE
Update from upstream, with fork migrations

### PR DESCRIPTION
**Pull request by dracos**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Is there any way to have the Permalinkable mixin be turned on/off with a feature flag, so that this fork can be merged back into upstream?

**Comment by jpmckinney** [comment]
Maybe something like this (somewhat pseudocode) in `django-popolo/popolo/behaviors/models.py`:

```python
if django_settings.popolo_autoslug:
    class Permalinkable(models.Model):
      # class as currently implemented
else:
    class Permalinkable(models.Model):
      pass # of whatever minimal logic is necessary to not have errors
```

**Comment by mhl** [comment]
@jpmckinney Isn't there a problem here that you'll get different migrations generated with `popolo_autoslug` set to `True` or `False`? (Maybe you potentially could write migrations that are conditional on that config option, but that would be difficult to maintain and confusing, I think, even if it worked.)

**Comment by jpmckinney** [comment]
What's the downside of having an extra Django field / database column? The main thing is turning off the functionality that reads/uses that field/column.

**Comment by jpmckinney** [comment]
i.e. both branches if the if-statement can have [these lines](https://github.com/openpolis/django-popolo/blob/master/popolo/behaviors/models.py#L92-L101), but only the True branch has [these lines](https://github.com/openpolis/django-popolo/blob/master/popolo/behaviors/models.py#L103-L110).

**Comment by mhl** [comment]
Perhaps that would be OK for Permalinkable then (I haven't tried to see if it would work in practice).

A bigger problem, though, would be the `id` field being different, e.g. in upstream (openpolis) that's:

https://github.com/openpolis/django-popolo/blob/master/popolo/models.py#L39-L43

... whereas the mysociety fork uses the implicit integer primary key.

**Comment by jpmckinney** [comment]
Let's do one PR with everything else, and then one PR for the `id`. Having a non-integer `id` is weird; I think we can get something merged, it may just require more discussion.

**Comment by jpmckinney** [comment]
Anyway, are we agreed that it's better to have one open-source project instead of two forks, and that in the long term, investing in a few conversations now is less costly than tracking upstream like in this PR - or worse, losing track of upstream and having to maintain yet another project? If so, I can volunteer to write some of those PRs.

**Comment by mhl** [comment]
Personally, yes, I'd much prefer if we didn't have to maintain a fork. I think it may be tricky to arrange, given the `id` issue and the we have already have deployed code that's used the migrations in this `update-with-better-migrations-redux` (and that has a different initial migration from upstream so that the version used by SayIt could be migrated easily), but you're very welcome to try.

@dracos is away at the moment, but it would definitely be worth seeing what he thinks too.

**Comment by jpmckinney** [comment]
I figure you could always write a new migration for those deployments if necessary, and skip any migrations added to django-popolo if necessary. The challenges seem small and surmountable.

**Comment by jpmckinney** [comment]
I got most of the way there but now I can't remember the magic command to generate migrations within a Django app. I got as far as `django-admin.py makemigrations --settings settings` with a barebones settings.py, but then it complains about not finding settings in its path. If I add `--pythonpath=.` then it complains about not finding model_utils...

**Comment by jpmckinney** [comment]
Anyway, the strategy would be for upstream to migrate towards having regular integer IDs. If that works, then I think this fork can just skip that migration, as upstream would be migrating towards this fork. This fork may need to create and run a migration to add (unused) `slug` fields.

**Comment by dracos** [comment]
Hi, I believe I did try and do this at the time (there are other PRs from around the same period), but couldn't get it to work. Lots of things have changed since, from Django migrations to underlying slug code, so it may well be different now.

AutoSlugField does all its magic automatically on model save, so simply specifying it is enough to have it be read/used, I'm afraid; from a quick look it appears it would be okay to just (hiddenly) populate itself and deal with uniqueness clashes and so on, but it would need to be checked (Aside, it's a shame it overrides slugify to the most basic option.)

However, if 'slug' as a field is brought back into this fork, then anything using this fork will have to migrate to using a differently named field (e.g. SayIt already currently uses 'slug' itself on its subclass of the Person model, which would then clash and raise an exception). This will be confusing in that you'll have something called "slug" you don't use, and something called something else that you are using as the slug.

So whilst I'm also agreed that having one project would be better, of course, I also don't mind maintaining this from upstream; we have submitted any other changes we've made upstream, so we are not drifting apart in that sense, and would continue to do so. The docs could be updated to point upstream, explaining the reason this fork exists.

**Comment by jpmckinney** [comment]
Thanks for explaining! And indulging my suggestion. Would it make sense to document the changes you identify in the changelog, or point to these comments from somewhere?

**Pull request merged**
